language: ruby
cache: bundler
install:
  - bundle install --path vendor/bundle
before_script:
  - rake build
script:
  - rake test_html
env:
  global:
    secure: EnUSbIxao5m8JzzI7F/3/bQ4KAN9uiFcjtKX5a7YM0JaOYJYJbQb9h+1vVOgKXeC81+rNBiko6C1aRXua0oHskUMf/ugNJA8nZKMlL24n5S2Z3P1mtUGbpUQYib4m7jxApsIEvkHs9t/LWe5pYIvMR3BFAEtu5cKCOchLeU69u4E67dO8GWQfY4+O9nhliHNZFl2ifgB8SbV2t9vpspi9l9yz767jjRrl9qAoy++tfgIFw9QX0rZE53aJKuicojAECYyLD8nQ76OUaAop/qI946yMemlFrnmdBSXe73aw45gzndJIujyD0Lgf1B58jbp6hM266mB+vLMYG3gLz1bkO7lyqRO70/TyOzD3tb5MIe6X6rmPEOv+BlzyUF7Dr64iwE3g63WcSMXeqXOiB5U7TWQsTvaucY3pTAONWdFEKY4RBpLdw2PmuHNAfDc3zxXPX2zFcY57Mj8ZsYrb7UIw65whQfN/vEVxMfw14gevwQiAc7c3drGlwGgN+v8ku+zS1oYvcjw9vsXh8zPut/ubaRpkkW0REWC9uEJrk4yG1rE+nUwlG+NSPzU9wtOH9L+y1FaBaml1KBXeKkoC1Scbq7m9D62+Pu2/iw0m0dt4FJwBvCYCqjAEbkpzjjL5oBajaO7y92GIYz0xY4p9QwGZYuYiuE11ACyvg/QPFV8Qbg=
