language: ruby
cache: bundler
install:
  - bundle install --path vendor/bundle
before_script:
  - cp .env.example .env
  - rake build
script:
  - rake test
deploy:
  provider: script
  script: rake deploy
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    - secure: BAMTdqeEOsVmrcBSGqs0uPjNqCgB2cYqKPnIiIaApt5xzpjYrCe+HdZYMdVLJ4XZBibtm5PsvI99vZXgdeLJZBOJKj6p8xKRuPoL9mol2j+Sz6sbTI93JKOKIRJSZ6wsPFlUKHiSXVvVOlMpd/xt/hxFEmXEnmRCCtkwDRKYFUDTOwIzd2czwj3NE6YTC0DRAW0EaBTxADgIzQVN53l8y4zhSn+ta+GG7Z/oXfH1+ysuWlk4L7jD7Jkk5phmaTDMcI2fVxxGeeksSOrLiuPOonK7tENysDq/YfAvYgqa9AdYQIm7a37DejP5th7sPm0gnIT5Np6z7iVI3M76PTnAdBVsyGDi4ucRBmiIb/HLPQK8zx98cvmJ9KKTpB3KEFWZv/6L0Sott7eThs8BpNTj2cJsftWoVJXMFtjIVtrPI8Q4c5JBiumszR0CErT4xOkQ3ak9u0VRsZL0MVz455W6rcv9sODiAfYhMNwdGZPJkhP69EzMTG+QblL/ctADI2/rertKoPocBoaDUPqpQNcuHPiDqfMPZVzyOXCcUjCapFAyah0PEyX+q6e/XtPIVqDHVoeRaiJ6XTWhF297JL34oQcAh4lKl0SVSsCn0tfXQZ5RKHnndWPSYLu5ZA2hCJaeCazifFozipiyshZJTbUdxd3HesECSKCUGKRt9P8mLBw=
    - secure: EQEbYa8aHAf6xMoZwAVNVEY5PsbG/q1T0y2nDXtMYyHvmMqeT7l0SZoIG1tuC/vv1eZE13QYq/Lp99pTS3Os7s2gcBbne6SBvAaxj+u0PK5p6v0OMTU7z8lRBTUid2szQa1Oht2IEPCsiiIi23UG7kesdXWBHLRwAs+N1Zmn4joY8/JTaIlgY0a8PXWoKQgxBnZovtCapGU0iV7TcUucb3753H8Kx59EHBKjJhwo/srmd7MhjLS7pST5OfR/NomM34+EmN1eD/AZya45nC2zkjCPKXB7g7oHrGU3lfVBsFQym/Gx8z/PNB33H0X/H1ACw4sYv/HHYQ/Hyk+huU9wpu0YjnnZl4Oe11WL7gs8ZykDYo04/LaPWA91BDhnxYEeEL3NQ6LceMzFcfnl2OyWO6eybueqoPj9KWK+qf2EQ6Xlmm7xxGHibikyc1AZFpDVr99pAnmKl6a1+scvskUOvtZLqT2ZekxYMn9y4Yf6Wxr13YHqmh4RRJEyRoXTvTh8+c05mXfpIxd1ErIePuHd47liwJR+ts2k8UIv5pplLG2jwDRN5H2FS9VDaxuA9dArSXd6Tu0l8AO2jcCIWjVSrHX4Su0p3MEuSGa61TBss74cou9pVfEOHWfSRI2XDAKAnyeEipor3Pq2SE9ExwT/puoxaUrgOqac1FLD7/VRU7g=
