language: ruby
cache: bundler
install:
  - bundle install --path vendor/bundle
before_script:
  - rake build
  - rake docker_build
  - rake docker_run
script:
  - rake test_html
  - rake docker_test
deploy:
  provider: script
  script: rake docker_deploy
  on:
    branch: master
env:
  global:
    - secure: SyXHqNLS2cJyk+MheUOlvlfV1t/pUerUHICshZPP1JQC2X8IxvFPE7d6hI/ycpMaWt8BqQKG5/5Q7jMCyO71wh3cG+8gMhLMDqxO2sPaLG5fcs1IqHRk/6AEureNAIhZE804b8ISjV+PEfGlyzw4bNukGMF0HohkQXiNOR2xO9rEAfgYJXDUgffw8pSXeAw7B04085l0rl7wKkF5HAOf61yWXVnZ0fefHNUJvfj+QgmCsYIemYhZNgGoOQUrE53T54OP13HdLhM266NRdl0r7LgrNbfB92403MjQ0ZRRleaUxW/oyA+CamIozyx99Ci758kbR4BjbBHRBjZFwnBKhZkXsqX2XKZTmJ+Y1PBiVfwuzElIRXfwIJ37WVrEIwRq6Z1A4M+Z7F0VVgQ7M6DV89W8wSMCdhdCjMBwHJkednx3+FdqoZB1qmT35wlZMZB1TWXvX8jlh9oyly9OYowAjX41tsJQY7Fo5LmUTkT1qYsZRsBvSgXL7QR4Q1mAgFBp8Mh4s8UDDc2w9uIEjaKO/hv5TsJ+rbW2Chs9HwpLWlbeH9sgDPVI/grbYGofVGn0pv4TVQBWKOdhLFrxyiFF75Kl7Ke20C0Lxihdej50pPv/V6NhT372+atR0+dpLyf8LZv3C6Wa0PtavVo9ddK2Aulswg+jrVYhjoPbi3+WP9M=
    - secure: lnaSEMpd6sbeCYpeUeaaqSpX0Ufz6tE5G1yAkU8BCfyLUC1i54ZydJw2L7j12I1M6Q40+Jv/d8Ryo1fP2bt+0+3oNj4hbt3ZdVJlZyVwZA3Od1ynN7YBl3JAKRr8O6w+TaOHKjKFs8DJpZplq6UTALRnTg7sEeylx9BZDcfaj6i8jXvB6sfE+ukh67TfcU7fq8SDTn9B9ikqVqALzIYb0GJrGUXqR7rtb+pPVe/TnT08SQmBv5dq7rUp3Sq31HLkIexLKM/GE66Czub0N0m6c32CKLDsC8Kx3PvxnWttTuYZl6Qi8McQZmyYiwMFMlYodKbOf5t4+sGYZTDf4rcI2Y/WtyVoW1P4Zr2MFEm7zf3yprcOnyhO43ZeVOnCypvM5TM5cK9iTWJIQlF9ot1iBIjiQaPi8KrYL1ekHASc+syaZ0h08CAeFMXjZP/fQsURgqLxyb9UqtGJtD7kypq7OC00vqdz285wjcXJUr+6XArIJCPiZfCq3STFWHFzD1JEe6Ol3W3/JQQD0xRhsrMJTdcwvdWPas3CgCxG0uCkxZRJlF9tHVkyY20MCXvu0R8D0z/gAd5a3iJbFa32QAWWn9tAZjHwMUj137svUYUAUzsGPTB6fOBciAO12fBe+g3hgMe2YO8LzlmoOvQeMHTCRDfBXrdytkVgtwUT1B1zl6M=
    - secure: RWZYbOTZ6HBBF8kxGJ/brSL1DDGjWtDqdyT4zqJIbOS651gnefiqWMxpzkdQBiV35MEWxO7/57hvpNIeiYYhqA0+ne5XaG5ggLblkhIMjbY6Nt56knetpm5nbLM/jwJQXk0JL380xOw/vs8rUlTHmTENHjHArUxo5T3yqNvHl47EkDiYsSus7j2D3o8orsgrMqXye6GwI+pm5ke955/56/8UQXSv5XJDtX1RpR6dlLwW8npqQH3K5pLOFn5QvfTeC5yrvAbefS+fKwZwiJZnI5mqPJk76wRdTeqm69ZARIYbNp9Zei0wV1xA9DLnCmbd2hYrnhc/7CVDSGWFamzbU7CSIMHc6+oEOGCJwlYMSqZD9S/Ir/4vb/szg4JQtroEYwM9X734ly6OE5c4HIae9i3Mz/DvgV8Et6bIJFVBV5+Fc+sngv8ssf5kDY8y4Sq5cwlBOmmycj4JmRNT4pjNnj+Eip5omXfe5pLhMGbHqdUWeXAqInqjM4AzXtfxHnKtUUzvqX/AM68gCGJR/unFDyDwTgu849bxlc9k6l2bPC3sTtG4SOjuFjMWerGqWdkEQWcP68YqpaoTj6V/ARKHcepZ0bRSHvkBLCEoZgsh9O/BuE61pSO3n44Gb9CJulhT3+3+B9CLNCY6CQrjX2AFxma++dFrV55cT0iTn8qGY00=
