language: ruby
cache:
  directories:
  - "./vendor/bundle"
  - "./.asset-cache"
install:
- bundle install --path vendor/bundle
before_script:
- bundle exec rake generate_links
- bundle exec rake generate_updates
script:
- bundle exec rake build
# deploy:
# - provider: pages
#   github-token: "$GITHUB_TOKEN"
#   target-branch: gh-pages
#   local-dir: build
#   name: pietbot
#   email: hi+pietbot@pietvanzoen.com
#   keep-history: true
#   skip_cleanup: true
#   verbose: true
#   on:
#     branch: master
env:
  global:
  - BUILD_DIR='./build'
  - secure: oZgOHYfmFka563rITtqivHzz7uuvSp+7I3H9M9ZIcKqteHlz/UkB8VN+azc5hbrXW5bJI3ZMSZYqBdKNm+jfYvivG4SQtQLy0HFZzAcyovFbvrL5rXrsw1/4bGngyYH6AN9R267peQjiqp3BF6a9zYmx+/QdoVsoheCyC04kYZFIakXrLQZzt1tUiJUKVn83rxFJqvobtx1QOWQz6305NmO+Oi+1hnYpzUJaRI85vjMGadz0yT/ZlLgJKq0H6lCy2cSQTtkof23aAGiSDtj/rpUqfY8Rd2gyaNoG6Vaa2JTtatzTFCPW11qQFKT313snxqkaa9FcMWReA5+OVIRhM9sGSu5L6lasWqXe+7rOIt91+CI1dcrbHiHn45BKjTXWZ6am6CoF7Irn/VxWGoqPKTFCdVDzOUUzwAR28DV9wtNPYladvrd4LvyRg+4irPqu20FwyiPlxrTdCDCWQS8DcU51BBmShHEvpsPooQPlNi4Dldr6DSfeph3sprERgSEU+q92uKu6Q40SOATKwQHk+6Ru93TDTc9DusX1HHL0LgleGEgW72HvPX//sXYo7fcHCxGkbqs5KkkYK2gQznf1nGkx/A4RDUtcsecdbAiYV8Tdn2S7ouI7aX+W0jwP71KAqBR4MirpxwcR3PNnh7/FrIOUNxNzm6kMcEU/bTRaR8M=
  - secure: OdgKydRKCwZiy7OKfsy948s2qMMUg0jeEjlNtqLZ/uMQgR3yB/VF2kEGeQPwI8lAL5nmIjS0hAFKKCVcC4cHALzkSNA/WlfzzKBColL9jZWQPHuonGREd5wlFvCoxxE9mQTA6wX5YMcfbTC3zw29vlFxkDxfgrwpWq/oznC4Y3XK0sZJa2bN0s35/XjDBajmoGd7ChZvMaAndY+wqs+nV+Hz0rvSgE1UFnLi9mAi+P9BFC4jtRL5vMiGNKq3fpPxC34BDV8WC1mIz0lZwL7EI7pknM7Eprof2qgNc0FDku2FbHlJ8oxQDAhcg01g1SY/k+4XOpW1XzbZPUHeMH9Sctd9E3uugP6sxu93/80ZV5gRFSIJFPtUZO9C8uFxLSLh8L2HN7RadGsjZ1B34hYSHfbMXger/cEqFOEPQ1HFakZ031v/GuKqccREeZwsCzh1KJ8eBL9eSw75FaPkmmuAqcSKIEq350kZ2xMi2hOMRVrSftUo/gHNSKqyeGK3/x9+kti1YTD1eJ8SBPUY6ZgbelxFEWcerrPQe1w8erx4Xhg+U0ZJ0KlXnBWSLvQcipeKpem4kin+FNgppRFmDa1gPoWNvooafJSqqstRM0Lz2bQXcDx0uKrmFtuS5kgfaxN4mYAH6qfTXUb09n2KyTdX1ebk+5+qOj3pDzQN1vgqldg=
