language: ruby
cache: bundler
install:
  - bundle install --path vendor/bundle
before_script:
  - rake build
  - rake docker_build
  - rake docker_run
script:
  - rake test_html
  - rake docker_test
deploy:
  provider: script
  script: rake docker_deploy
  on:
    branch: travis
env:
  global:
    - secure: EnUSbIxao5m8JzzI7F/3/bQ4KAN9uiFcjtKX5a7YM0JaOYJYJbQb9h+1vVOgKXeC81+rNBiko6C1aRXua0oHskUMf/ugNJA8nZKMlL24n5S2Z3P1mtUGbpUQYib4m7jxApsIEvkHs9t/LWe5pYIvMR3BFAEtu5cKCOchLeU69u4E67dO8GWQfY4+O9nhliHNZFl2ifgB8SbV2t9vpspi9l9yz767jjRrl9qAoy++tfgIFw9QX0rZE53aJKuicojAECYyLD8nQ76OUaAop/qI946yMemlFrnmdBSXe73aw45gzndJIujyD0Lgf1B58jbp6hM266mB+vLMYG3gLz1bkO7lyqRO70/TyOzD3tb5MIe6X6rmPEOv+BlzyUF7Dr64iwE3g63WcSMXeqXOiB5U7TWQsTvaucY3pTAONWdFEKY4RBpLdw2PmuHNAfDc3zxXPX2zFcY57Mj8ZsYrb7UIw65whQfN/vEVxMfw14gevwQiAc7c3drGlwGgN+v8ku+zS1oYvcjw9vsXh8zPut/ubaRpkkW0REWC9uEJrk4yG1rE+nUwlG+NSPzU9wtOH9L+y1FaBaml1KBXeKkoC1Scbq7m9D62+Pu2/iw0m0dt4FJwBvCYCqjAEbkpzjjL5oBajaO7y92GIYz0xY4p9QwGZYuYiuE11ACyvg/QPFV8Qbg=
    - secure: I2rkkqLI+GAtunbDIYorOHaVWNFI0MsJRkEzRrM/AJjmFIuYQven//gxBSoxNxvVVLhrSEVxO4qkbDTe0+2/oE5fAeOrlRbo/35LI7H+1YEzz24KYz/RYCgMIAiaL12x7QBjOiGtE/NTNu1hzQ6r9mt0vlyulsfRQC42hDtju5Lk6a1p+DzhTcAVSPtQwYolRcsxkmTbbNTcoVPAsqtgVIvD/NwSBFfMHoIOKwW7JO9OraZ0TmLrS+xgOfDTZ4aPO3kQK2oMOsAQIt2w7gEZSB/pVgLj3WGtP7J7bWJkeAkjwIxHhPVO8qaWA6OOeHEQxBHztm95eQFCgySZZOopbJk3lLjbw5onv6bJmluktEqImi/dxa6McoUr7wXAUjtxzm2FjidbEvBHirADLBwgGH+MtGOrLACJk24CemqyE140wX4Qroqp5OBoumC/oz9fd6Kljgg+KgF5bz8kOkDyXO8eX6fY3/5jE/b6UzbkGYI0Powe8qzulWBgSgfkySlVF79AyUOi5vDaGOIGLpzShfYkFZmiWpreW37bZLJGSNogzqg2dJSplG4Xc9SDoYCyxkNfY2U176jPJACTGLhiyOJkM5YzeT9X5RmJTqJLHVuQzEtEx6Js8rRLWnVPijjm1DbcPAPERxw+ifGxPVSViHlF8D+e8jg05wmgFnpvERI=
    - secure: lslN5XHqbXqUjlaq2+l1KfnKnrj8W734gea+Sxo0OE4IYcNzhJQcWYY00iZvDNn2SbcUy9t1+5Rz6cC1k+j7b+0AoP/IaC1dUHdzh/73xg9XpnhjYuLIaNbCmPS2PJjihX6vlmvd8Jz/vrAZs/2+EXhYIpjTiwHdf0oGA1+hB9XysUiq3R9pV8U8U3Hov++HsHeOaMXLQn59HszfaYxTTE9XLIGpcRPAOiXMGBOaRSUFRFwAxad7pRb43IVthd4OFWF2ZLmTAcebvNt3YKsLVWiPxVLVJhZlP4/StYWvmy7F95DPKI+w0fCw36juqcvrirvIi4xK7Kzo1XfIOKsYPjbv+NLCyqHrLuZj8iNwBdryOdDmenBaInAVp1jVKOnGoXbStWOhviVJT8UB2Br76UiyXIODiyCko0BaGzROOBtCRWFxPNObc6630WM3d4vsMJp5AjvVxdfm5/P5d9CzL8jS1fJwryRYkZbb4DgTUWBdxocykNTVWVD9vMeQ/fkp73tjKfKEIKPbztwfok2DPobK/4M1ac5aS3kAH1D/8hfi0RWhs1Bzm5wR59/rxR3U6F+MJdD1zgWdA8opVBkT3WqTOQYAEbXyTDXTKxaf9yO5ZXnjC1CaQS9MLsiqe2QZ8W+33P4Pmkk2HT8fW91f2uCnGHj4TwGkCBYP0+H4dcU=
