name: Piet van Zoen
description: Portland based dutch/englishman and web developer at Cozy.
url: http://pietvanzoen.com

markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
highligher: true
main_title: Piet van Zoen | Portland based web developer.

permalink: /:categories/:title

exclude: ["CNAME"]
