name: Piet van Zoen
description: Portland based dutch/englishman and web developer at Cozy.
url: http://pietvanzoen.com

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
main_title: Piet van Zoen | Portland based web developer.

permalink: /:categories/:title

exclude: ["CNAME"]

gems:
  - jekyll-redirect-from
