name: Piet van Zoen
description: Portland based dutch/englishman and web developer at Daylight Studio.
url: http://pietvanzoen.com

markdown: redcarpet
pygments: true
main_title: Piet van Zoen | Portland based web developer.

permalink: /:categories/:title

exclude: ["CNAME"]
