version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/project/vendor/bundle
      - run: bundle exec middleman build
      - run: bundle exec ruby test.rb
      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project/build

  deploy:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - run: bundle --path vendor/bundle
      - run:
          name: deploy
          command: |
            cp -r .circleci ./source
            git config user.email $GIT_USER_EMAIL
            git config user.name $GIT_USER_NAME
            bundle exec middleman deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: dist
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - deploy:
          requires:
            - build
