backend:
  name: github
  repo: pietvanzoen/pietvanzoen.com
  base_url: https://netlify-cms-oauth.piet.me

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: blog
    label: Blog
    folder: source/blog/
    extension: .html.md
    format: frontmatter
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Publish Date, name: date, widget: datetime, required: true}
      - {label: Update Date, name: date, widget: datetime, required: false}
      - {label: "Unsplash Image", name: "unsplash_img_id", widget: "string", required: false}
      - {label: "Image Alt", name: "img_alt", widget: "string", required: false}
      - {label: "Published", name: published, widget: boolean, default: false, required: true}
      - {label: Body, name: body, widget: markdown, required: true}
