name: Auto Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Ruby Version
      run: |
        ruby -v

    - name: Setup Cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Setup Ruby Dependencies
      run: |
        gem update bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Import content
      env:
        RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }}
      run: |
        rake generate_links
        rake generate_updates

    - name: Build
      env:
        BUILD_DIR: './build'
      run: |
        rake build

    - name: Store build
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build

    # - name: Deploy to branch
    #   uses: peaceiris/actions-gh-pages@v1.1.0
    #   if: success()
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     PUBLISH_BRANCH: dist
    #     PUBLISH_DIR: ./build
