name: Main Build

on:
  push:
  repository_dispatch:
    types: trigger-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Ruby Version
      run: |
        ruby -v

    - name: Setup Cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Setup Ruby Dependencies
      run: |
        gem update bundler
        bundle config path vendor/bundle
        bundle check || bundle install --jobs 4 --retry 3

    - name: Import content
      env:
        RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }}
      run: |
        rake generate_links
        rake generate_updates

    - name: Build
      env:
        BUILD_DIR: './build'
        ENV: production
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      run: |
        rake build

    - name: Store build
      uses: actions/upload-artifact@v1
      if: github.ref == 'refs/heads/master'
      with:
        name: build-${{ github.sha }}
        path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: build-${{ github.sha }}
        path: build

    - name: Deploy to branch
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build
